// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Aceptadoestado
{
    public int Id { get; set; }

    public string Estado { get; set; }

    public string Descripcion { get; set; }
    [JsonIgnore]
    public virtual ICollection<Registroestado> Registroestado { get; set; } = new List<Registroestado>();
    [JsonIgnore]
    public virtual ICollection<Transaccion> Transaccion { get; set; } = new List<Transaccion>();
}