// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Aceptadoestado
{
    public int Id { get; set; }

    public string Estado { get; set; }

    public string Descripcion { get; set; }
    
    //public virtual ICollection<Registroestado> IdRegistroestado { get; set; } = new List<Registroestado>();
    
   // public virtual ICollection<Transaccion> IdTransaccion { get; set; } = new List<Transaccion>();
}