// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Bancoestado
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }
    
    //public virtual ICollection<Banco> NombreBanco { get; set; } = new List<Banco>();
}