// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Registroestado
{
    public int Id { get; set; }

    public DateOnly FechaHora { get; set; }

    public int IdValidadoEstado { get; set; }

    public int IdAceptadoEstado { get; set; }

    public int IdTransaccion { get; set; }
    [JsonIgnore]
    public virtual Aceptadoestado IdAceptadoEstadoNavigation { get; set; }
    [JsonIgnore]
    public virtual Transaccion IdTransaccionNavigation { get; set; }
    [JsonIgnore]
    public virtual Validacionestado IdValidadoEstadoNavigation { get; set; }
}