// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Registroestado
{
    public int Id { get; set; }

    public DateTime FechaHora { get; set; }

    public int IdValidadoEstado { get; set; }

    public int IdAceptadoEstado { get; set; }

    public int IdTransaccion { get; set; }

    public virtual Aceptadoestado IdAceptadoEstadoNavigation { get; set; }

    public virtual Transaccion IdTransaccionNavigation { get; set; }

    public virtual Validacionestado IdValidadoEstadoNavigation { get; set; }
}