// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Transaccion
{
    public int Id { get; set; }

    public float Monto { get; set; }

    public DateOnly FechaHora { get; set; }

    public int IdTipo { get; set; }

    public int IdValidacionEstado { get; set; }

    public int IdAceptadoEstado { get; set; }

    public int IdCuentaOrigen { get; set; }

    public int IdCuentaDestino { get; set; }

    public int Numero { get; set; }
    [JsonIgnore]
    public virtual Aceptadoestado IdAceptadoEstadoNavigation { get; set; }
    [JsonIgnore]
    public virtual Cuenta IdCuentaDestinoNavigation { get; set; }
    [JsonIgnore]
    public virtual Cuenta IdCuentaOrigenNavigation { get; set; }
    [JsonIgnore]
    public virtual Tipo IdTipoNavigation { get; set; }
    [JsonIgnore]
    public virtual Validacionestado IdValidacionEstadoNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Registroestado> Registroestado { get; set; } = new List<Registroestado>();
}