// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Validacionestado
{
    public int Id { get; set; }

    public string Estado { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Registroestado> Registroestado { get; set; } = new List<Registroestado>();

    public virtual ICollection<Transaccion> Transaccion { get; set; } = new List<Transaccion>();
}